/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface MediaCreateResponse {
    meta?: Ittybit.MediaCreateResponseMeta;
    data?: Ittybit.MediaCreateResponseData;
    links?: Ittybit.MediaCreateResponseLinks;
}
