/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Visual orientation.
 */
export type MediaGetResponseDataSourcesItemOrientation = "landscape" | "portrait" | "square";
export const MediaGetResponseDataSourcesItemOrientation = {
    Landscape: "landscape",
    Portrait: "portrait",
    Square: "square",
} as const;
