/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The primary kind of the media item, derived from its sources.
 */
export type MediaGetResponseDataKind = "video" | "image" | "audio" | "document" | "unknown";
export const MediaGetResponseDataKind = {
    Video: "video",
    Image: "image",
    Audio: "audio",
    Document: "document",
    Unknown: "unknown",
} as const;
