/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MediaGetResponseMeta {
    id?: string;
    method?: string;
    url?: string;
    version?: string;
    status?: number;
    org_id?: string;
    project_id?: string;
    object?: string;
    created?: string;
}
