/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface MediaGetResponse {
    meta?: Ittybit.MediaGetResponseMeta;
    data?: Ittybit.Media;
    links?: Ittybit.MediaGetResponseLinks;
}
