/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface MediaDeleteResponse {
    meta?: Ittybit.MediaDeleteResponseMeta;
    data?: Ittybit.MediaDeleteResponseData;
    links?: Ittybit.MediaDeleteResponseLinks;
}
