/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The general type of media (e.g., video, image).
 */
export type MediaCreateResponseDataSourcesItemKind = "video" | "image" | "audio" | "document" | "unknown";
export const MediaCreateResponseDataSourcesItemKind = {
    Video: "video",
    Image: "image",
    Audio: "audio",
    Document: "document",
    Unknown: "unknown",
} as const;
