/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         url: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
 *         folder: "examples/cartoons",
 *         filename: "bunny.mp4",
 *         metadata: {
 *             "credit": "gtv-videos-bucket"
 *         }
 *     }
 */
export interface MediaCreateRequest {
    /** URL of the media file to ingest. Required unless 'empty' is true. */
    url?: string;
    /** Label for the media */
    label?: string;
    /** Folder to store the media in */
    folder?: string;
    /** Filename for the media */
    filename?: string;
    /** Title for the media */
    title?: string;
    /** Additional metadata for the media */
    metadata?: Record<string, unknown>;
    /** Whether to process the media asynchronously */
    async?: boolean;
    /** Create an empty media placeholder */
    empty?: boolean;
}
