/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface MediaListRequest {
    /**
     * Page number for pagination.
     */
    page?: number;
    /**
     * Number of media items to return per page.
     */
    limit?: number;
}
