/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface MediaUpdateRequest {
    /** New title for the media item. */
    title?: string;
    /** New metadata object for the media item. This will replace the existing metadata. */
    metadata?: Record<string, unknown>;
}
