/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface SignaturesCreateResponse {
    meta?: Ittybit.SignaturesCreateResponseMeta;
    data?: Ittybit.SignaturesCreateResponseData;
    links?: Ittybit.SignaturesCreateResponseLinks;
}
