/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SignaturesCreateRequestMethod = "get" | "put";
export const SignaturesCreateRequestMethod = {
    Get: "get",
    Put: "put",
} as const;
