/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Optional HTTP method allowed for the signed URL. Defaults to 'get'.
 */
export type SignaturesCreateRequestMethod = "get" | "put" | "post" | "delete";
export const SignaturesCreateRequestMethod = {
    Get: "get",
    Put: "put",
    Post: "post",
    Delete: "delete",
} as const;
