/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface GetApiExampleResponse {
    meta?: Ittybit.GetApiExampleResponseMeta;
    data?: Record<string, unknown>;
}
