/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../../index";

/**
 * @example
 *     {}
 */
export interface TasksListRequest {
    /**
     * Items per page.
     */
    limit?: number;
    /**
     * Filter by task status.
     */
    status?: Ittybit.TasksListRequestStatus;
    /**
     * Filter by task kind.
     */
    kind?: Ittybit.TasksListRequestKind;
}
