/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../../index";

/**
 * @example
 *     {
 *         kind: "ingest",
 *         url: "https://example.com/some_video.mov",
 *         input: {
 *             "options": {
 *                 "filename": "custom_name.mov"
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         kind: "ingest",
 *         url: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
 *         filename: "bunny-1280x720.mp4",
 *         folder: "examples/cartoons",
 *         width: 1280,
 *         height: 720
 *     }
 */
export interface TasksCreateRequest {
    /** The type of task to create. */
    kind: Ittybit.TasksCreateRequestKind;
    /** URL of the source file (required for 'ingest' kind unless file_id is used, can be used for others). */
    url?: string;
    /** Task-specific input parameters depending on the kind of task. */
    input?: Record<string, unknown>;
    /** ID of an existing file to use as input (alternative to url). */
    file_id?: string;
    /** An array of task definition objects for a workflow. */
    workflow?: Record<string, unknown>[];
    /** An optional HTTPS URL to send a webhook notification to upon task completion or failure. */
    webhook_url?: string;
    /** Desired filename for the output (if applicable). */
    filename?: string;
    /** Desired output folder (if applicable). */
    folder?: string;
    /** Output format (e.g., for video/image tasks). */
    format?: string;
    /** Output width (for video/image tasks). */
    width?: number;
    /** Output height (for video/image tasks). */
    height?: number;
    /** Output quality setting (e.g., for video/image tasks, 0-100). */
    quality?: number;
}
