/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../../index";

/**
 * @example
 *     {}
 */
export interface TasksListFilteredRequest {
    /**
     * Page number.
     */
    page?: number;
    /**
     * Items per page.
     */
    limit?: number;
    /**
     * Filter by task status.
     */
    status?: Ittybit.TasksListFilteredRequestStatus;
    /**
     * Filter by task kind.
     */
    kind?: Ittybit.TasksListFilteredRequestKind;
}
