/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface FilesDeleteResponse {
    /** Contains a confirmation message */
    data?: Ittybit.FilesDeleteResponseData;
    meta?: Ittybit.Meta | undefined;
    links?: Ittybit.Links;
}
