/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface FilesListResponse {
    meta?: Ittybit.FilesListResponseMeta;
    data?: Ittybit.FilesListResponseDataItem[];
    links?: Ittybit.FilesListResponseLinks;
}
