/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export type FilesGetResponseData = Ittybit.File_ | Ittybit.FilesGetResponseDataAnalysis;
