/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface FilesGetResponse {
    meta?: Ittybit.FilesGetResponseMeta;
    data?: Ittybit.FilesGetResponseData;
    links?: Ittybit.FilesGetResponseLinks;
}
