/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FilesGetResponseDataAnalysis {
    id?: string;
    media_id?: string;
    object?: string;
    kind?: string;
    format?: string;
    type?: string;
    width?: number;
    height?: number;
    filesize?: number;
    filename?: string;
    url?: string;
    created?: string;
    updated?: string;
    duration?: number;
    fps?: number;
    folder?: string;
    created_by?: string;
    metadata?: Record<string, unknown>;
    analysis?: Record<string, unknown>;
    original?: boolean;
}
