/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface FilesDeleteResponse {
    data?: Ittybit.FilesDeleteResponseData;
    meta?: Ittybit.FilesDeleteResponseMeta;
    links?: Ittybit.FilesDeleteResponseLinks;
}
