/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface FilesListResponse extends Ittybit.ApiResponseBase {
    /** List of file objects */
    data?: unknown[];
}
