/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface FilesCreateFromUrlResponse {
    meta?: Ittybit.FilesCreateFromUrlResponseMeta;
    data?: Ittybit.FilesCreateFromUrlResponseData;
    links?: Ittybit.FilesCreateFromUrlResponseLinks;
}
