/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface FilesUpdateMetadataResponse {
    meta?: Ittybit.FilesUpdateMetadataResponseMeta;
    data?: Ittybit.FilesUpdateMetadataResponseData;
    links?: Ittybit.FilesUpdateMetadataResponseLinks;
}
