/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface FilesDeleteResponse extends Ittybit.ApiResponseBase {
    /** Contains a confirmation message */
    data?: Ittybit.FilesDeleteResponseData;
}
