/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Contains a confirmation message
 */
export interface FilesDeleteResponseData {
    /** Confirmation message */
    message?: string;
}
