/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface ApiResponseBase {
    meta?: Ittybit.ApiResponseBaseMeta;
    links?: Ittybit.ApiResponseBaseLinks;
}
