/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Base structure for standard API responses.
 */
export interface ApiResponseBase {
    meta?: Ittybit.Meta;
    links?: Ittybit.Links;
}
