/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AutomationResponseDataTriggerConditionsItem {
    /** The property to check (e.g., file.type, file.size) */
    prop: string;
    /** The value the property must match */
    value: string;
}
