/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for Automation list responses.
 */
export interface AutomationListResponse extends Ittybit.ApiResponseBase {
    data?: Ittybit.Automation[];
}
