/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Represents an automated workflow triggered by specific events.
 */
export interface Automation {
    /** Unique identifier for the automation */
    id: string;
    /** User-defined name for the automation */
    name: string;
    /** Optional description for the automation */
    description?: string;
    /** The event and conditions that trigger this automation. */
    trigger: Ittybit.AutomationTrigger;
    /** The sequence of tasks to be executed when the automation is triggered. The structure of each task object varies depending on its 'kind'. */
    workflow: Ittybit.WorkflowTaskStep[];
    /** Current status of the automation */
    status: Ittybit.AutomationStatus;
    /** Timestamp when the automation was created */
    created: string;
    /** Timestamp when the automation was last updated */
    updated: string;
}
