/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface AutomationListResponse {
    meta?: Ittybit.MetaList;
    data?: Ittybit.Automation[];
    links?: Ittybit.LinksList;
}
