/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface Automation {
    id: string;
    name?: string;
    description?: string;
    trigger: Ittybit.AutomationTrigger;
    workflow: Ittybit.AutomationWorkflowItem[];
    status: Ittybit.AutomationStatus;
    created: string;
    updated: string;
}
