/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface AutomationListResponse {
    meta?: Ittybit.AutomationListResponseMeta;
    data?: Ittybit.AutomationListResponseDataItem[];
    links?: Ittybit.AutomationListResponseLinks;
}
