/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for single Automation responses.
 */
export interface AutomationResponse extends Ittybit.ApiResponseBase {
    data?: Ittybit.Automation;
}
