/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface AutomationResponse {
    meta?: Ittybit.Meta | undefined;
    data?: Ittybit.Automation;
    error?: Ittybit.Error_;
    links?: Ittybit.Links;
}
