/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface BadRequestErrorBody {
    meta?: Ittybit.BadRequestErrorBodyMeta;
    error?: Ittybit.BadRequestErrorBodyError;
}
