/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface ConfirmationResponse {
    meta?: Ittybit.ConfirmationResponseMeta;
    data?: Ittybit.ConfirmationResponseData;
    links?: Ittybit.ConfirmationResponseLinks;
}
