/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for confirmation message responses.
 */
export interface ConfirmationResponse extends Ittybit.ApiResponseBase {
    data?: Ittybit.ConfirmationResponseData;
}
