/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ID of the entity that created the task (e.g., user ID, automation ID).
 */
export type CreatedBy = string | undefined;
