/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard error response format.
 */
export interface Error_ {
    meta?: Ittybit.Meta;
    /** Error message */
    error?: string;
}
