/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FileObject = "source" | "track" | "intelligence";
export const FileObject = {
    Source: "source",
    Track: "track",
    Intelligence: "intelligence",
} as const;
