/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface File_ {
    id: string;
    media_id: string;
    object: Ittybit.FileObject;
    kind: Ittybit.FileKind;
    type: string;
    codec?: string;
    container?: string;
    width?: number;
    height?: number;
    orientation?: string;
    rotation?: number;
    transparency?: boolean;
    animated?: boolean;
    frames?: number;
    duration?: number;
    fps?: number;
    filesize: number;
    bitrate?: number;
    language?: string;
    label?: string;
    ref?: string;
    folder?: string;
    filename?: string;
    url: string;
    placeholder?: string;
    background?: string;
    metadata?: Record<string, unknown>;
    original?: boolean;
    created_by?: string;
    created: string;
    updated: string;
    status: Ittybit.FileStatus;
}
