/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The general type of media.
 */
export type FileResponseDataKind = "video" | "image" | "audio" | "document" | "unknown";
export const FileResponseDataKind = {
    Video: "video",
    Image: "image",
    Audio: "audio",
    Document: "document",
    Unknown: "unknown",
} as const;
