/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface FileListResponse {
    meta?: Ittybit.FileListResponseMeta;
    data?: Ittybit.FileListResponseDataItem[];
    links?: Ittybit.FileListResponseLinks;
}
