/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface FileResponse {
    meta?: Ittybit.FileResponseMeta;
    data?: Ittybit.FileResponseData;
    links?: Ittybit.FileResponseLinks;
}
