/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for single File responses.
 */
export interface FileResponse extends Ittybit.ApiResponseBase {
    data?: Ittybit.File_;
}
