/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FileStatus = "waiting" | "processing" | "ready" | "failed";
export const FileStatus = {
    Waiting: "waiting",
    Processing: "processing",
    Ready: "ready",
    Failed: "failed",
} as const;
