/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for File list responses.
 */
export interface FileListResponse extends Ittybit.ApiResponseBase {
    data?: Ittybit.File_[];
}
