/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FileKind = "video" | "image" | "audio";
export const FileKind = {
    Video: "video",
    Image: "image",
    Audio: "audio",
} as const;
