/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface ForbiddenErrorBody {
    meta?: Ittybit.ForbiddenErrorBodyMeta;
    error?: Ittybit.ForbiddenErrorBodyError;
}
