/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Links {
    /** The absolute URL of the current request, potentially including query parameters. */
    self?: string;
    /** URL for the parent resource. */
    parent?: string;
}
