/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MediaResponseMeta {
    /** Request ID */
    request_id?: string;
    /** Type of the primary data object in the response (e.g., list, object) */
    type?: string;
    /** Number of items per page. */
    limit?: number;
    /** Total number of items matching the query. */
    total?: number;
    /** Current page number. */
    page?: number;
    /** Total number of pages. */
    pages?: number;
}
