/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for single Media responses.
 */
export interface MediaResponse extends Ittybit.ApiResponseBase {
    data?: Ittybit.Media;
}
