/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MediaSourceObject = "source" | "track" | "intelligence";
export const MediaSourceObject = {
    Source: "source",
    Track: "track",
    Intelligence: "intelligence",
} as const;
