/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Processing status.
 */
export type MediaResponseDataStatus = "processing" | "ready" | "failed" | "pending";
export const MediaResponseDataStatus = {
    Processing: "processing",
    Ready: "ready",
    Failed: "failed",
    Pending: "pending",
} as const;
