/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for Media list responses.
 */
export interface MediaListResponse extends Ittybit.ApiResponseBase {
    data?: Ittybit.Media[];
}
