/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MediaSourceOrientation = "landscape" | "portrait" | "square";
export const MediaSourceOrientation = {
    Landscape: "landscape",
    Portrait: "portrait",
    Square: "square",
} as const;
