/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface MediaSource {
    id: string;
    object: Ittybit.MediaSourceObject;
    kind: Ittybit.MediaSourceKind;
    type: string;
    codec?: string;
    container?: string;
    width?: number;
    height?: number;
    orientation?: Ittybit.MediaSourceOrientation;
    rotation?: number;
    transparency?: boolean;
    frames?: number;
    duration?: number;
    fps?: number;
    filesize: number;
    bitrate?: number;
    ref?: string;
    folder?: string;
    filename?: string;
    url: string;
    metadata?: Record<string, unknown>;
    original?: boolean;
    created: string;
    updated: string;
    status: Ittybit.MediaSourceStatus;
}
