/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface Media {
    id: string;
    object: string;
    kind?: Ittybit.MediaKind;
    title?: string;
    alt?: string;
    width?: number;
    height?: number;
    duration?: number;
    files: Ittybit.MediaSource[];
    urls: Record<string, unknown>;
    background?: string;
    metadata?: Record<string, unknown>;
    created: string;
    updated: string;
}
