/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface MetaList {
    request_id?: string;
    org_id?: string;
    project_id?: string;
    version?: string;
    type?: Ittybit.MetaListType;
    limit?: number;
    total?: number;
    page?: number;
    pages?: number;
}
