/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Standard metadata included in API responses.
 */
export interface Meta {
    /** Request ID */
    id?: string;
    /** Organisation ID associated with the request */
    org_id?: string;
    /** Project ID associated with the request */
    project_id?: string;
    /** Type of the primary data object in the response (e.g., list, object) */
    object?: string;
    /** Whether the response is a list of objects. */
    list?: boolean;
    /** Number of items per page. */
    limit?: number;
    /** Total number of items matching the query. */
    total?: number;
    /** Current page number. */
    page?: number;
    /** Total number of pages. */
    pages?: number;
}
