/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MetaList {
    /** Request ID */
    request_id?: string;
    /** Type of the primary data value in the response */
    type?: "list";
    /** Number of items per page. */
    limit?: number;
    /** Total number of items matching the query. */
    total?: number;
    /** Current page number. */
    page?: number;
    /** Total number of pages. */
    pages?: number;
}
