/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MetaListType = "object" | "list";
export const MetaListType = {
    Object: "object",
    List: "list",
} as const;
