/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface NotFoundErrorBody {
    meta?: Ittybit.Meta;
    /** Error message */
    error?: string;
}
