/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for Signature responses.
 */
export interface SignatureResponse extends Ittybit.ApiResponseBase {
    data?: Ittybit.Signature;
}
