/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface SignatureResponse {
    meta?: Ittybit.SignatureResponseMeta;
    data?: Ittybit.SignatureResponseData;
    links?: Ittybit.SignatureResponseLinks;
}
