/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TaskSummaryKind =
    | "video"
    | "image"
    | "audio"
    | "chapters"
    | "subtitles"
    | "thumbnails"
    | "speech"
    | "description"
    | "nsfw"
    | "prompt"
    | "outline"
    | "http"
    | "ingest"
    | "workflow"
    | "conditions";
export const TaskSummaryKind = {
    Video: "video",
    Image: "image",
    Audio: "audio",
    Chapters: "chapters",
    Subtitles: "subtitles",
    Thumbnails: "thumbnails",
    Speech: "speech",
    Description: "description",
    Nsfw: "nsfw",
    Prompt: "prompt",
    Outline: "outline",
    Http: "http",
    Ingest: "ingest",
    Workflow: "workflow",
    Conditions: "conditions",
} as const;
