/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface TaskListResponse {
    meta?: Ittybit.TaskListResponseMeta;
    data?: Ittybit.TaskListResponseDataItem[];
    links?: Ittybit.TaskListResponseLinks;
}
