/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface TaskSummary {
    id: string;
    object: string;
    kind: Ittybit.TaskSummaryKind;
    status: Ittybit.TaskSummaryStatus;
    progress?: number;
    error?: string;
    created_by?: string;
    created: string;
    updated: string;
    parent_id?: string;
}
