/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for single Task responses.
 */
export interface TaskResponse {
    meta?: Ittybit.Meta;
    data?: Ittybit.Task;
    links?: Ittybit.Links;
}
