/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface Task {
    id: string;
    object: string;
    kind?: Ittybit.TaskKind;
    input?: Record<string, unknown>;
    options?: Record<string, unknown>;
    output?: Record<string, unknown>;
    status: Ittybit.TaskStatus;
    progress?: number;
    error?: string;
    created_by?: string;
    created: string;
    updated: string;
    parent_id?: string;
    workflow?: unknown[];
    results?: Ittybit.TaskResults;
}
