/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface TaskListResponse {
    meta?: Ittybit.MetaList;
    data?: Ittybit.Task[];
    links?: Ittybit.LinksList;
}
