/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

/**
 * Standard wrapper for Task list responses.
 */
export interface TaskListResponse extends Ittybit.ApiResponseBase {
    data?: Ittybit.Task[];
}
