/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TaskListResponseDataItemResults {
    passed?: Record<string, unknown>[];
    failed?: Record<string, unknown>[];
    continue?: boolean;
}
