/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface UnauthorizedErrorBody {
    meta?: Ittybit.UnauthorizedErrorBodyMeta;
    error?: Ittybit.UnauthorizedErrorBodyError;
}
