/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WorkflowTaskStepKind =
    | "video"
    | "image"
    | "audio"
    | "chapters"
    | "subtitles"
    | "thumbnails"
    | "nsfw"
    | "speech"
    | "description"
    | "outline"
    | "prompt"
    | "http";
export const WorkflowTaskStepKind = {
    Video: "video",
    Image: "image",
    Audio: "audio",
    Chapters: "chapters",
    Subtitles: "subtitles",
    Thumbnails: "thumbnails",
    Nsfw: "nsfw",
    Speech: "speech",
    Description: "description",
    Outline: "outline",
    Prompt: "prompt",
    Http: "http",
} as const;
