/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index";

export interface WorkflowTaskStep {
    kind: Ittybit.WorkflowTaskStepKind;
    ref?: string;
    next?: Ittybit.WorkflowTaskStepNextItem[];
}
