/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface TasksGetResponse {
    meta?: Ittybit.TasksGetResponseMeta;
    data?: Ittybit.TasksGetResponseData;
    links?: Ittybit.TasksGetResponseLinks;
}
