/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of task to create.
 */
export type TasksCreateRequestKind =
    | "ingest"
    | "workflow"
    | "speech"
    | "video"
    | "image"
    | "audio"
    | "summary"
    | "describe"
    | "chapters"
    | "outline"
    | "subtitles"
    | "nsfw"
    | "thumbnails";
export const TasksCreateRequestKind = {
    Ingest: "ingest",
    Workflow: "workflow",
    Speech: "speech",
    Video: "video",
    Image: "image",
    Audio: "audio",
    Summary: "summary",
    Describe: "describe",
    Chapters: "chapters",
    Outline: "outline",
    Subtitles: "subtitles",
    Nsfw: "nsfw",
    Thumbnails: "thumbnails",
} as const;
