/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface TasksCreateResponse {
    meta?: Ittybit.TasksCreateResponseMeta;
    data?: Ittybit.TasksCreateResponseData;
    links?: Ittybit.TasksCreateResponseLinks;
}
