/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

/**
 * Defines the trigger event and conditions. To clear/remove a trigger, provide null. To update, provide the new trigger object.
 */
export interface AutomationsUpdateRequestTrigger {
    /** The event that triggers the automation */
    event?: string;
    /** Conditions that must be met for the trigger to activate. */
    conditions?: Ittybit.AutomationsUpdateRequestTriggerConditionsItem[];
}
