/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface AutomationsCreateResponse {
    meta?: Ittybit.AutomationsCreateResponseMeta;
    data?: Ittybit.AutomationsCreateResponseData;
    links?: Ittybit.AutomationsCreateResponseLinks;
}
