/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AutomationsUpdateRequestStatus = "active" | "paused";
export const AutomationsUpdateRequestStatus = {
    Active: "active",
    Paused: "paused",
} as const;
