/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface AutomationsUpdateResponseData {
    /** Unique identifier for the automation */
    id: string;
    /** User-defined name for the automation */
    name: string;
    /** Optional description for the automation */
    description?: string;
    /** User-defined key-value metadata for the automation. */
    metadata?: Record<string, unknown>;
    /** The event and conditions that trigger this automation. */
    trigger: Ittybit.AutomationsUpdateResponseDataTrigger;
    /** The sequence of tasks to be executed when the automation is triggered. The structure of each task object varies depending on its 'kind'. */
    workflow: Ittybit.AutomationsUpdateResponseDataWorkflowItem[];
    /** Current status of the automation */
    status: Ittybit.AutomationsUpdateResponseDataStatus;
    /** Timestamp when the automation was created */
    created: string;
    /** Timestamp when the automation was last updated */
    updated: string;
}
