/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AutomationsCreateRequestStatus = "active" | "paused";
export const AutomationsCreateRequestStatus = {
    Active: "active",
    Paused: "paused",
} as const;
