/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface AutomationsUpdateRequestWorkflowItem {
    /** The type of operation the task performs. */
    kind: Ittybit.AutomationsUpdateRequestWorkflowItemKind;
    /** Optional label for the output of this step. */
    label?: string;
    /** Output format (e.g., mp4, jpg) */
    format?: string;
    /** Output width */
    width?: number;
    /** Output height */
    height?: number;
    /** Resize mode */
    resize?: string;
    /** Quality setting */
    quality?: number;
}
