/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface AutomationsListResponse extends Ittybit.ApiResponseBase {
    /** List of automation objects */
    data?: unknown[];
}
