/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Current status of the automation
 */
export type AutomationsUpdateResponseDataStatus = "active" | "inactive" | "draft";
export const AutomationsUpdateResponseDataStatus = {
    Active: "active",
    Inactive: "inactive",
    Draft: "draft",
} as const;
