/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface AutomationsListResponse {
    meta?: Ittybit.AutomationsListResponseMeta;
    data?: Ittybit.AutomationsListResponseDataItem[];
    links?: Ittybit.AutomationsListResponseLinks;
}
