/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

/**
 * The event and conditions that trigger this automation.
 */
export interface AutomationsGetResponseDataTrigger {
    /** The event that triggers the automation */
    event: string;
    /** Conditions that must be met for the trigger to activate. */
    conditions?: Ittybit.AutomationsGetResponseDataTriggerConditionsItem[];
}
