/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface AutomationsUpdateResponse {
    meta?: Ittybit.AutomationsUpdateResponseMeta;
    data?: Ittybit.AutomationsUpdateResponseData;
    links?: Ittybit.AutomationsUpdateResponseLinks;
}
