/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface AutomationsGetResponse {
    meta?: Ittybit.AutomationsGetResponseMeta;
    data?: Ittybit.AutomationsGetResponseData;
    links?: Ittybit.AutomationsGetResponseLinks;
}
