/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of operation the task performs.
 */
export type AutomationsUpdateResponseDataWorkflowItemKind =
    | "ingest"
    | "workflow"
    | "speech"
    | "outline"
    | "chapters"
    | "subtitles"
    | "thumbnails"
    | "nsfw"
    | "summary"
    | "describe"
    | "video"
    | "image"
    | "audio"
    | "http"
    | "conditions"
    | "store"
    | "prompt"
    | "tags";
export const AutomationsUpdateResponseDataWorkflowItemKind = {
    Ingest: "ingest",
    Workflow: "workflow",
    Speech: "speech",
    Outline: "outline",
    Chapters: "chapters",
    Subtitles: "subtitles",
    Thumbnails: "thumbnails",
    Nsfw: "nsfw",
    Summary: "summary",
    Describe: "describe",
    Video: "video",
    Image: "image",
    Audio: "audio",
    Http: "http",
    Conditions: "conditions",
    Store: "store",
    Prompt: "prompt",
    Tags: "tags",
} as const;
