/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateAutomationRequestStatus = "active" | "paused";
export const UpdateAutomationRequestStatus = {
    Active: "active",
    Paused: "paused",
} as const;
