/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../../index";

/**
 * @example
 *     {
 *         name: "Transcode Uploaded Videos (Updated)",
 *         trigger: [{
 *                 "event": "media.ready",
 *                 "conditions": [
 *                     {
 *                         "prop": "media.kind",
 *                         "value": "image"
 *                     }
 *                 ]
 *             }]
 *     }
 */
export interface AutomationsUpdateRequest {
    name: string;
    description?: string;
    trigger: Record<string, unknown>[];
    /** The updated sequence of tasks for the automation. */
    workflow?: Ittybit.WorkflowTaskStep[];
}
