/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../../index";

/**
 * @example
 *     {
 *         name: "Updated Transcoder Example",
 *         trigger: {
 *             event: "upload.completed",
 *             conditions: [{
 *                     prop: "file.type",
 *                     value: "image/*"
 *                 }]
 *         },
 *         workflow: [{
 *                 kind: "image",
 *                 label: "archive_image",
 *                 format: "webp"
 *             }]
 *     }
 */
export interface AutomationsUpdateRequest {
    name: string;
    description?: string;
    /** Defines the trigger event and conditions. To clear/remove a trigger, provide null. To update, provide the new trigger object. */
    trigger?: Ittybit.AutomationsUpdateRequestTrigger;
    /** The updated sequence of tasks for the automation. */
    workflow?: Ittybit.AutomationsUpdateRequestWorkflowItem[];
}
