/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../../index";

/**
 * @example
 *     {
 *         name: "My Updated Automation",
 *         workflow: [{
 *                 kind: "nsfw"
 *             }, {
 *                 kind: "description"
 *             }, {
 *                 kind: "image",
 *                 ref: "big_thumbnail"
 *             }, {
 *                 kind: "conditions",
 *                 next: [{
 *                         kind: "subtitle",
 *                         ref: "subtitle"
 *                     }]
 *             }],
 *         status: "active"
 *     }
 */
export interface UpdateAutomationRequest {
    name?: string;
    description?: string;
    trigger?: Ittybit.UpdateAutomationRequestTrigger;
    workflow?: Ittybit.WorkflowTaskStep[];
    status?: Ittybit.UpdateAutomationRequestStatus;
}
