/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         url: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
 *         filename: "bunny.mp4",
 *         folder: "examples/cartoons",
 *         metadata: {
 *             "credit": "gtv-videos-bucket"
 *         }
 *     }
 */
export interface FilesCreateRequest {
    /** The publicly accessible URL of the file to ingest. */
    url: string;
    /** Optional desired filename. If not provided, it may be derived from the URL. */
    filename?: string;
    /** Folder path (optional) */
    folder?: string;
    /** Optional existing media ID to associate the file with. */
    media_id?: string;
    /** Optional label for the file. */
    label?: string;
    /** Optional user-defined key-value metadata. */
    metadata?: Record<string, unknown>;
    /** Whether to process the ingestion asynchronously. */
    async?: boolean;
}
