/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface FilesListRequest {
    /**
     * Page number
     */
    page?: number;
    /**
     * Items per page
     */
    limit?: number;
}
