/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         metadata: {
 *             "status": "approved",
 *             "reviewed_by": "user_abc"
 *         }
 *     }
 *
 * @example
 *     {
 *         filename: "final_approved_video.mp4",
 *         folder: "archive/2024"
 *     }
 */
export interface FilesUpdateMetadataRequest {
    /** An object containing key-value pairs to set or update. Set a key to null to remove it. */
    metadata?: Record<string, unknown>;
    /** New filename for the file. */
    filename?: string;
    /** New folder path for the file. */
    folder?: string;
}
