/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../../index";

/**
 * @example
 *     {
 *         filename: "video.mp4",
 *         folder: "example",
 *         expiry: 1735689600,
 *         method: "put"
 *     }
 */
export interface SignaturesCreateRequest {
    filename: string;
    folder?: string;
    expiry?: number;
    method?: Ittybit.SignaturesCreateRequestMethod;
}
