/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../index";

export interface GetBillingResponse {
    org?: Record<string, unknown>;
    store?: Ittybit.GetBillingResponseStore;
    ledger?: Ittybit.GetBillingResponseLedger;
}
