/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetBillingResponseStore {
    plan?: Record<string, unknown>;
    usage?: Record<string, unknown>;
    used_percentage?: number;
}
