/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Automations } from "./api/resources/automations/client/Client";
import { Files } from "./api/resources/files/client/Client";
import { Media } from "./api/resources/media/client/Client";
import { Tasks } from "./api/resources/tasks/client/Client";
import { Signatures } from "./api/resources/signatures/client/Client";

export declare namespace IttybitClient {
    export interface Options {
        environment?: core.Supplier<environments.IttybitEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the Accept-Version header */
        acceptVersion: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the Accept-Version header */
        acceptVersion?: string;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class IttybitClient {
    protected _automations: Automations | undefined;
    protected _files: Files | undefined;
    protected _media: Media | undefined;
    protected _tasks: Tasks | undefined;
    protected _signatures: Signatures | undefined;

    constructor(protected readonly _options: IttybitClient.Options) {}

    public get automations(): Automations {
        return (this._automations ??= new Automations(this._options));
    }

    public get files(): Files {
        return (this._files ??= new Files(this._options));
    }

    public get media(): Media {
        return (this._media ??= new Media(this._options));
    }

    public get tasks(): Tasks {
        return (this._tasks ??= new Tasks(this._options));
    }

    public get signatures(): Signatures {
        return (this._signatures ??= new Signatures(this._options));
    }
}
